//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Types.Game.Guild.Tax
{
    using MageBot.Protocol.Types.Game.Context.Roleplay;


    public class TaxCollectorGuildInformations : TaxCollectorComplementaryInformations
    {
        
        protected override int ProtocolId { get; set; } = 446;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private BasicGuildInformations m_guild;
        
        public virtual BasicGuildInformations Guild
        {
            get
            {
                return m_guild;
            }
            set
            {
                m_guild = value;
            }
        }
        
        public TaxCollectorGuildInformations(BasicGuildInformations guild)
        {
            m_guild = guild;
        }
        
        public TaxCollectorGuildInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            m_guild.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_guild = new BasicGuildInformations();
            m_guild.Deserialize(reader);
        }
    }
}
