//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System;


    [Serializable()]
    public class LegendaryTreasureHunt : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual uint Level
        {
            get
            {
                return mLevel;
            }
            set
            {
                mLevel = value;
            }
        }
        
        private uint mLevel;
        
        public virtual uint ChestId
        {
            get
            {
                return mChestId;
            }
            set
            {
                mChestId = value;
            }
        }
        
        private uint mChestId;
        
        public virtual uint MonsterId
        {
            get
            {
                return mMonsterId;
            }
            set
            {
                mMonsterId = value;
            }
        }
        
        private uint mMonsterId;
        
        public virtual uint MapItemId
        {
            get
            {
                return mMapItemId;
            }
            set
            {
                mMapItemId = value;
            }
        }
        
        private uint mMapItemId;
        
        public virtual double XpRatio
        {
            get
            {
                return mXpRatio;
            }
            set
            {
                mXpRatio = value;
            }
        }
        
        private double mXpRatio;
        
        public LegendaryTreasureHunt()
        {
        }
    }
}
