//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Context.Roleplay.TreasureHunt
{
    public class TreasureHuntLegendaryRequestMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 6499;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_legendaryId;
        
        public virtual ushort LegendaryId
        {
            get
            {
                return m_legendaryId;
            }
            set
            {
                m_legendaryId = value;
            }
        }
        
        public TreasureHuntLegendaryRequestMessage(ushort legendaryId)
        {
            m_legendaryId = legendaryId;
        }
        
        public TreasureHuntLegendaryRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_legendaryId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_legendaryId = reader.ReadVarUhShort();
        }
    }
}
