//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class PartyMemberRemoveMessage : AbstractPartyEventMessage 
    {
        
        public new const int ID = 5579;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private ulong m_leavingPlayerId;
        
        public virtual ulong LeavingPlayerId
        {
            get
            {
                return m_leavingPlayerId;
            }
            set
            {
                m_leavingPlayerId = value;
            }
        }
        
        public PartyMemberRemoveMessage(ulong leavingPlayerId)
        {
            m_leavingPlayerId = leavingPlayerId;
        }
        
        public PartyMemberRemoveMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarLong(m_leavingPlayerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_leavingPlayerId = reader.ReadVarUhLong();
        }
    }
}
