//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Fight
{
    using BlueSheep.Common.Protocol.Types.Game.Context.Fight;
    using System.Collections.Generic;


    public class GameFightResumeWithSlavesMessage : GameFightResumeMessage
    {
        
        public const int ProtocolId = 6215;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<GameFightResumeSlaveInfo> m_slavesInfo;
        
        public virtual List<GameFightResumeSlaveInfo> SlavesInfo
        {
            get
            {
                return m_slavesInfo;
            }
            set
            {
                m_slavesInfo = value;
            }
        }
        
        public GameFightResumeWithSlavesMessage(List<GameFightResumeSlaveInfo> slavesInfo)
        {
            m_slavesInfo = slavesInfo;
        }
        
        public GameFightResumeWithSlavesMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(((short)(m_slavesInfo.Count)));
            int slavesInfoIndex;
            for (slavesInfoIndex = 0; (slavesInfoIndex < m_slavesInfo.Count); slavesInfoIndex = (slavesInfoIndex + 1))
            {
                GameFightResumeSlaveInfo objectToSend = m_slavesInfo[slavesInfoIndex];
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            int slavesInfoCount = reader.ReadUShort();
            int slavesInfoIndex;
            m_slavesInfo = new System.Collections.Generic.List<GameFightResumeSlaveInfo>();
            for (slavesInfoIndex = 0; (slavesInfoIndex < slavesInfoCount); slavesInfoIndex = (slavesInfoIndex + 1))
            {
                GameFightResumeSlaveInfo objectToAdd = new GameFightResumeSlaveInfo();
                objectToAdd.Deserialize(reader);
                m_slavesInfo.Add(objectToAdd);
            }
        }
    }
}
