//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class AchievementReward : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual uint AchievementId
        {
            get
            {
                return mAchievementId;
            }
            set
            {
                mAchievementId = value;
            }
        }
        
        private uint mAchievementId;
        
        public virtual int LevelMin
        {
            get
            {
                return mLevelMin;
            }
            set
            {
                mLevelMin = value;
            }
        }
        
        private int mLevelMin;
        
        public virtual int LevelMax
        {
            get
            {
                return mLevelMax;
            }
            set
            {
                mLevelMax = value;
            }
        }
        
        private int mLevelMax;
        
        public virtual List<uint> ItemsReward
        {
            get
            {
                return mItemsReward;
            }
            set
            {
                mItemsReward = value;
            }
        }
        
        private List<uint> mItemsReward = new List<uint>();
        
        public virtual List<uint> ItemsQuantityReward
        {
            get
            {
                return mItemsQuantityReward;
            }
            set
            {
                mItemsQuantityReward = value;
            }
        }
        
        private List<uint> mItemsQuantityReward = new List<uint>();
        
        public virtual List<uint> EmotesReward
        {
            get
            {
                return mEmotesReward;
            }
            set
            {
                mEmotesReward = value;
            }
        }
        
        private List<uint> mEmotesReward = new List<uint>();
        
        public virtual List<uint> SpellsReward
        {
            get
            {
                return mSpellsReward;
            }
            set
            {
                mSpellsReward = value;
            }
        }
        
        private List<uint> mSpellsReward = new List<uint>();
        
        public virtual List<uint> TitlesReward
        {
            get
            {
                return mTitlesReward;
            }
            set
            {
                mTitlesReward = value;
            }
        }
        
        private List<uint> mTitlesReward = new List<uint>();
        
        public virtual List<uint> OrnamentsReward
        {
            get
            {
                return mOrnamentsReward;
            }
            set
            {
                mOrnamentsReward = value;
            }
        }
        
        private List<uint> mOrnamentsReward = new List<uint>();
        
        public AchievementReward()
        {
        }
    }
}
