//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.Context.Mount
{
    using BlueSheep.Protocol;


    public class MountEquipedErrorMessage : Message
    {
        
        public const int ProtocolId = 5963;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_errorType;
        
        public virtual byte ErrorType
        {
            get
            {
                return m_errorType;
            }
            set
            {
                m_errorType = value;
            }
        }
        
        public MountEquipedErrorMessage(byte errorType)
        {
            m_errorType = errorType;
        }
        
        public MountEquipedErrorMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_errorType);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_errorType = reader.ReadByte();
        }
    }
}
