//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.Inventory.Exchanges
{
    using BlueSheep.Protocol.Types.Game.Data.Items;
    using System.Collections.Generic;
    using BlueSheep.Protocol;


    public class ExchangeBidHouseUnsoldItemsMessage : Message
    {
        
        public const int ProtocolId = 6612;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<ObjectItemGenericQuantity> m_items;
        
        public virtual List<ObjectItemGenericQuantity> Items
        {
            get
            {
                return m_items;
            }
            set
            {
                m_items = value;
            }
        }
        
        public ExchangeBidHouseUnsoldItemsMessage(List<ObjectItemGenericQuantity> items)
        {
            m_items = items;
        }
        
        public ExchangeBidHouseUnsoldItemsMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort(((short)(m_items.Count)));
            int itemsIndex;
            for (itemsIndex = 0; (itemsIndex < m_items.Count); itemsIndex = (itemsIndex + 1))
            {
                ObjectItemGenericQuantity objectToSend = m_items[itemsIndex];
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            int itemsCount = reader.ReadUShort();
            int itemsIndex;
            m_items = new System.Collections.Generic.List<ObjectItemGenericQuantity>();
            for (itemsIndex = 0; (itemsIndex < itemsCount); itemsIndex = (itemsIndex + 1))
            {
                ObjectItemGenericQuantity objectToAdd = new ObjectItemGenericQuantity();
                objectToAdd.Deserialize(reader);
                m_items.Add(objectToAdd);
            }
        }
    }
}
