//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Types.Game.Context.Fight
{


    public class FightTeamMemberTaxCollectorInformations : FightTeamMemberInformations
    {
        
        protected override int ProtocolId { get; set; } = 177;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_firstNameId;
        
        public virtual ushort FirstNameId
        {
            get
            {
                return m_firstNameId;
            }
            set
            {
                m_firstNameId = value;
            }
        }
        
        private ushort m_lastNameId;
        
        public virtual ushort LastNameId
        {
            get
            {
                return m_lastNameId;
            }
            set
            {
                m_lastNameId = value;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        private uint m_guildId;
        
        public virtual uint GuildId
        {
            get
            {
                return m_guildId;
            }
            set
            {
                m_guildId = value;
            }
        }
        
        private uint m_uid;
        
        public virtual uint Uid
        {
            get
            {
                return m_uid;
            }
            set
            {
                m_uid = value;
            }
        }
        
        public FightTeamMemberTaxCollectorInformations(ushort firstNameId, ushort lastNameId, sbyte level, uint guildId, uint uid)
        {
            m_firstNameId = firstNameId;
            m_lastNameId = lastNameId;
            m_level = level;
            m_guildId = guildId;
            m_uid = uid;
        }
        
        public FightTeamMemberTaxCollectorInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarShort(m_firstNameId);
            writer.WriteVarShort(m_lastNameId);
            writer.WriteSByte(m_level);
            writer.WriteVarInt(m_guildId);
            writer.WriteVarInt(m_uid);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_firstNameId = reader.ReadVarUhShort();
            m_lastNameId = reader.ReadVarUhShort();
            m_level = reader.ReadSByte();
            m_guildId = reader.ReadVarUhInt();
            m_uid = reader.ReadVarUhInt();
        }
    }
}
