//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System;


    [Serializable()]
    public class AlignmentEffect : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint CharacteristicId
        {
            get
            {
                return mCharacteristicId;
            }
            set
            {
                mCharacteristicId = value;
            }
        }
        
        private uint mCharacteristicId;
        
        public virtual uint DescriptionId
        {
            get
            {
                return mDescriptionId;
            }
            set
            {
                mDescriptionId = value;
            }
        }
        
        private uint mDescriptionId;
        
        public AlignmentEffect()
        {
        }
    }
}
