//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay.Job
{
    using BlueSheep.Common.Protocol.Types.Game.Context.Roleplay.Job;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class JobCrafterDirectoryAddMessage : Message 
    {
        
        public new const int ID = 5651;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private JobCrafterDirectoryListEntry m_listEntry;
        
        public virtual JobCrafterDirectoryListEntry ListEntry
        {
            get
            {
                return m_listEntry;
            }
            set
            {
                m_listEntry = value;
            }
        }
        
        public JobCrafterDirectoryAddMessage(JobCrafterDirectoryListEntry listEntry)
        {
            m_listEntry = listEntry;
        }
        
        public JobCrafterDirectoryAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_listEntry.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_listEntry = new JobCrafterDirectoryListEntry();
            m_listEntry.Deserialize(reader);
        }
    }
}
