//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class LivingObjectSkinJntMood : IData
    {
        
        public virtual int SkinId
        {
            get
            {
                return mSkinId;
            }
            set
            {
                mSkinId = value;
            }
        }
        
        private int mSkinId;
        
        public virtual List<List<int>> Moods
        {
            get
            {
                return mMoods;
            }
            set
            {
                mMoods = value;
            }
        }
        
        private List<List<int>> mMoods = new List<List<int>>();
        
        public LivingObjectSkinJntMood()
        {
        }
    }
}
