//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System;


    [Serializable()]
    public class FinishMove : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual int Duration
        {
            get
            {
                return mDuration;
            }
            set
            {
                mDuration = value;
            }
        }
        
        private int mDuration;
        
        public virtual bool Free
        {
            get
            {
                return mFree;
            }
            set
            {
                mFree = value;
            }
        }
        
        private bool mFree;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual int Category
        {
            get
            {
                return mCategory;
            }
            set
            {
                mCategory = value;
            }
        }
        
        private int mCategory;
        
        public virtual int SpellLevel
        {
            get
            {
                return mSpellLevel;
            }
            set
            {
                mSpellLevel = value;
            }
        }
        
        private int mSpellLevel;
        
        public FinishMove()
        {
        }
    }
}
