//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Paddock
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class PaddockBuyableInformations 
    {
        
        public new const int ID = 130;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ulong m_price;
        
        public virtual ulong Price
        {
            get
            {
                return m_price;
            }
            set
            {
                m_price = value;
            }
        }
        
        private bool m_locked;
        
        public virtual bool Locked
        {
            get
            {
                return m_locked;
            }
            set
            {
                m_locked = value;
            }
        }
        
        public PaddockBuyableInformations(ulong price, bool locked)
        {
            m_price = price;
            m_locked = locked;
        }
        
        public PaddockBuyableInformations()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            writer.WriteVarLong(m_price);
            writer.WriteBoolean(m_locked);
        }
        
        public void Deserialize(IDataReader reader)
        {
            m_price = reader.ReadVarUhLong();
            m_locked = reader.ReadBoolean();
        }
    }
}
