//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Prism
{
    public class PrismFightJoinLeaveRequestMessage : Message
    {
        
        public override int ProtocolId { get; } = 5843;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_subAreaId;
        
        public virtual ushort SubAreaId
        {
            get
            {
                return m_subAreaId;
            }
            set
            {
                m_subAreaId = value;
            }
        }
        
        private bool m_join;
        
        public virtual bool Join
        {
            get
            {
                return m_join;
            }
            set
            {
                m_join = value;
            }
        }
        
        public PrismFightJoinLeaveRequestMessage(ushort subAreaId, bool join)
        {
            m_subAreaId = subAreaId;
            m_join = join;
        }
        
        public PrismFightJoinLeaveRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_subAreaId);
            writer.WriteBoolean(m_join);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_subAreaId = reader.ReadVarUhShort();
            m_join = reader.ReadBoolean();
        }
    }
}
