//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Types.Game.Shortcut
{
    using BlueSheep.Protocol.Types;


    public class Shortcut : NetworkType
    {
        
        protected override int ProtocolId { get; set; } = 369;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_slot;
        
        public virtual byte Slot
        {
            get
            {
                return m_slot;
            }
            set
            {
                m_slot = value;
            }
        }
        
        public Shortcut(byte slot)
        {
            m_slot = slot;
        }
        
        public Shortcut()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_slot);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_slot = reader.ReadByte();
        }
    }
}
