//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Script
{
    public class CinematicMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 6053;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_cinematicId;
        
        public virtual ushort CinematicId
        {
            get
            {
                return m_cinematicId;
            }
            set
            {
                m_cinematicId = value;
            }
        }
        
        public CinematicMessage(ushort cinematicId)
        {
            m_cinematicId = cinematicId;
        }
        
        public CinematicMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_cinematicId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_cinematicId = reader.ReadVarUhShort();
        }
    }
}
