//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Mount
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class MountHarnessColorsUpdateRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6697;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_useHarnessColors;
        
        public virtual bool UseHarnessColors
        {
            get
            {
                return m_useHarnessColors;
            }
            set
            {
                m_useHarnessColors = value;
            }
        }
        
        public MountHarnessColorsUpdateRequestMessage(bool useHarnessColors)
        {
            m_useHarnessColors = useHarnessColors;
        }
        
        public MountHarnessColorsUpdateRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_useHarnessColors);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_useHarnessColors = reader.ReadBoolean();
        }
    }
}
