//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Items
{
    using DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangePodsModifiedMessage : ExchangeObjectMessage
    {
        
        public const int ProtocolId = 6670;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_currentWeight;
        
        public virtual uint CurrentWeight
        {
            get
            {
                return m_currentWeight;
            }
            set
            {
                m_currentWeight = value;
            }
        }
        
        private uint m_maxWeight;
        
        public virtual uint MaxWeight
        {
            get
            {
                return m_maxWeight;
            }
            set
            {
                m_maxWeight = value;
            }
        }
        
        public ExchangePodsModifiedMessage(uint currentWeight, uint maxWeight)
        {
            m_currentWeight = currentWeight;
            m_maxWeight = maxWeight;
        }
        
        public ExchangePodsModifiedMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_currentWeight);
            writer.WriteVarUhInt(m_maxWeight);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_currentWeight = reader.ReadVarUhInt();
            m_maxWeight = reader.ReadVarUhInt();
        }
    }
}
