//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Inventory.Items
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class MimicryObjectEraseRequestMessage : Message 
    {
        
        public new const int ID = 6457;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private uint m_hostUID;
        
        public virtual uint HostUID
        {
            get
            {
                return m_hostUID;
            }
            set
            {
                m_hostUID = value;
            }
        }
        
        private sbyte m_hostPos;
        
        public virtual sbyte HostPos
        {
            get
            {
                return m_hostPos;
            }
            set
            {
                m_hostPos = value;
            }
        }
        
        public MimicryObjectEraseRequestMessage(uint hostUID, sbyte hostPos)
        {
            m_hostUID = hostUID;
            m_hostPos = hostPos;
        }
        
        public MimicryObjectEraseRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarInt(m_hostUID);
            writer.WriteSByte(m_hostPos);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_hostUID = reader.ReadVarUhInt();
            m_hostPos = reader.ReadSByte();
        }
    }
}
