//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class SoundBones : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual List<String> Keys
        {
            get
            {
                return mKeys;
            }
            set
            {
                mKeys = value;
            }
        }
        
        private List<String> mKeys = new List<String>();
        
        public virtual List<List<SoundAnimation>> Values
        {
            get
            {
                return mValues;
            }
            set
            {
                mValues = value;
            }
        }
        
        private List<List<SoundAnimation>> mValues = new List<List<SoundAnimation>>();
        
        public SoundBones()
        {
        }
    }
}
