//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Context.Roleplay
{
    using BlueSheep.Common.Protocol.Types.Game.Look;
    using BlueSheep.Common.Protocol.Types.Game.Context;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class GameRolePlayMountInformations : GameRolePlayNamedActorInformations
    {
        
        public new const int ID = 180;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private string m_ownerName;
        
        public virtual string OwnerName
        {
            get
            {
                return m_ownerName;
            }
            set
            {
                m_ownerName = value;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        public GameRolePlayMountInformations(string ownerName, sbyte level)
        {
            m_ownerName = ownerName;
            m_level = level;
        }
        
        public GameRolePlayMountInformations()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUTF(m_ownerName);
            writer.WriteSByte(m_level);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_ownerName = reader.ReadUTF();
            m_level = reader.ReadSByte();
        }
    }
}
