//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class CompanionCharacteristic : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual int CaracId
        {
            get
            {
                return mCaracId;
            }
            set
            {
                mCaracId = value;
            }
        }
        
        private int mCaracId;
        
        public virtual int CompanionId
        {
            get
            {
                return mCompanionId;
            }
            set
            {
                mCompanionId = value;
            }
        }
        
        private int mCompanionId;
        
        public virtual int Order
        {
            get
            {
                return mOrder;
            }
            set
            {
                mOrder = value;
            }
        }
        
        private int mOrder;
        
        public virtual List<List<double>> StatPerLevelRange
        {
            get
            {
                return mStatPerLevelRange;
            }
            set
            {
                mStatPerLevelRange = value;
            }
        }
        
        private List<List<double>> mStatPerLevelRange = new List<List<double>>();
        
        public CompanionCharacteristic()
        {
        }
    }
}
