//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System;


    [Serializable()]
    public class MonsterGrade : IData
    {
        
        public virtual uint Grade
        {
            get
            {
                return mGrade;
            }
            set
            {
                mGrade = value;
            }
        }
        
        private uint mGrade;
        
        public virtual int MonsterId
        {
            get
            {
                return mMonsterId;
            }
            set
            {
                mMonsterId = value;
            }
        }
        
        private int mMonsterId;
        
        public virtual uint Level
        {
            get
            {
                return mLevel;
            }
            set
            {
                mLevel = value;
            }
        }
        
        private uint mLevel;
        
        public virtual int Vitality
        {
            get
            {
                return mVitality;
            }
            set
            {
                mVitality = value;
            }
        }
        
        private int mVitality;
        
        public virtual int PaDodge
        {
            get
            {
                return mPaDodge;
            }
            set
            {
                mPaDodge = value;
            }
        }
        
        private int mPaDodge;
        
        public virtual int PmDodge
        {
            get
            {
                return mPmDodge;
            }
            set
            {
                mPmDodge = value;
            }
        }
        
        private int mPmDodge;
        
        public virtual int Wisdom
        {
            get
            {
                return mWisdom;
            }
            set
            {
                mWisdom = value;
            }
        }
        
        private int mWisdom;
        
        public virtual int EarthResistance
        {
            get
            {
                return mEarthResistance;
            }
            set
            {
                mEarthResistance = value;
            }
        }
        
        private int mEarthResistance;
        
        public virtual int AirResistance
        {
            get
            {
                return mAirResistance;
            }
            set
            {
                mAirResistance = value;
            }
        }
        
        private int mAirResistance;
        
        public virtual int FireResistance
        {
            get
            {
                return mFireResistance;
            }
            set
            {
                mFireResistance = value;
            }
        }
        
        private int mFireResistance;
        
        public virtual int WaterResistance
        {
            get
            {
                return mWaterResistance;
            }
            set
            {
                mWaterResistance = value;
            }
        }
        
        private int mWaterResistance;
        
        public virtual int NeutralResistance
        {
            get
            {
                return mNeutralResistance;
            }
            set
            {
                mNeutralResistance = value;
            }
        }
        
        private int mNeutralResistance;
        
        public virtual int GradeXp
        {
            get
            {
                return mGradeXp;
            }
            set
            {
                mGradeXp = value;
            }
        }
        
        private int mGradeXp;
        
        public virtual int LifePoints
        {
            get
            {
                return mLifePoints;
            }
            set
            {
                mLifePoints = value;
            }
        }
        
        private int mLifePoints;
        
        public virtual int ActionPoints
        {
            get
            {
                return mActionPoints;
            }
            set
            {
                mActionPoints = value;
            }
        }
        
        private int mActionPoints;
        
        public virtual int MovementPoints
        {
            get
            {
                return mMovementPoints;
            }
            set
            {
                mMovementPoints = value;
            }
        }
        
        private int mMovementPoints;
        
        public virtual int DamageReflect
        {
            get
            {
                return mDamageReflect;
            }
            set
            {
                mDamageReflect = value;
            }
        }
        
        private int mDamageReflect;
        
        public virtual uint HiddenLevel
        {
            get
            {
                return mHiddenLevel;
            }
            set
            {
                mHiddenLevel = value;
            }
        }
        
        private uint mHiddenLevel;
        
        public MonsterGrade()
        {
        }
    }
}
