//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.Alliance
{
    using BlueSheep.Protocol;


    public class AllianceInvitationStateRecruterMessage : Message
    {
        
        public const int ProtocolId = 6396;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private string m_recrutedName;
        
        public virtual string RecrutedName
        {
            get
            {
                return m_recrutedName;
            }
            set
            {
                m_recrutedName = value;
            }
        }
        
        private byte m_invitationState;
        
        public virtual byte InvitationState
        {
            get
            {
                return m_invitationState;
            }
            set
            {
                m_invitationState = value;
            }
        }
        
        public AllianceInvitationStateRecruterMessage(string recrutedName, byte invitationState)
        {
            m_recrutedName = recrutedName;
            m_invitationState = invitationState;
        }
        
        public AllianceInvitationStateRecruterMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUTF(m_recrutedName);
            writer.WriteByte(m_invitationState);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_recrutedName = reader.ReadUTF();
            m_invitationState = reader.ReadByte();
        }
    }
}
