//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class Skill : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual int ParentJobId
        {
            get
            {
                return mParentJobId;
            }
            set
            {
                mParentJobId = value;
            }
        }
        
        private int mParentJobId;
        
        public virtual bool IsForgemagus
        {
            get
            {
                return mIsForgemagus;
            }
            set
            {
                mIsForgemagus = value;
            }
        }
        
        private bool mIsForgemagus;
        
        public virtual List<int> ModifiableItemTypeIds
        {
            get
            {
                return mModifiableItemTypeIds;
            }
            set
            {
                mModifiableItemTypeIds = value;
            }
        }
        
        private List<int> mModifiableItemTypeIds = new List<int>();
        
        public virtual int GatheredRessourceItem
        {
            get
            {
                return mGatheredRessourceItem;
            }
            set
            {
                mGatheredRessourceItem = value;
            }
        }
        
        private int mGatheredRessourceItem;
        
        public virtual List<int> CraftableItemIds
        {
            get
            {
                return mCraftableItemIds;
            }
            set
            {
                mCraftableItemIds = value;
            }
        }
        
        private List<int> mCraftableItemIds = new List<int>();
        
        public virtual int InteractiveId
        {
            get
            {
                return mInteractiveId;
            }
            set
            {
                mInteractiveId = value;
            }
        }
        
        private int mInteractiveId;
        
        public virtual string UseAnimation
        {
            get
            {
                return mUseAnimation;
            }
            set
            {
                mUseAnimation = value;
            }
        }
        
        private string mUseAnimation;
        
        public virtual int Cursor
        {
            get
            {
                return mCursor;
            }
            set
            {
                mCursor = value;
            }
        }
        
        private int mCursor;
        
        public virtual int ElementActionId
        {
            get
            {
                return mElementActionId;
            }
            set
            {
                mElementActionId = value;
            }
        }
        
        private int mElementActionId;
        
        public virtual bool AvailableInHouse
        {
            get
            {
                return mAvailableInHouse;
            }
            set
            {
                mAvailableInHouse = value;
            }
        }
        
        private bool mAvailableInHouse;
        
        public virtual uint LevelMin
        {
            get
            {
                return mLevelMin;
            }
            set
            {
                mLevelMin = value;
            }
        }
        
        private uint mLevelMin;
        
        public virtual bool ClientDisplay
        {
            get
            {
                return mClientDisplay;
            }
            set
            {
                mClientDisplay = value;
            }
        }
        
        private bool mClientDisplay;
        
        public Skill()
        {
        }
    }
}
