//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay
{
    using BlueSheep.Common.Protocol.Types.Game.Context.Roleplay;
    using BlueSheep.Common.Protocol;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class GameRolePlayShowMultipleActorsMessage : Message 
    {
        
        public new const int ID = 6712;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private List<GameRolePlayActorInformations> m_informationsList;
        
        public virtual List<GameRolePlayActorInformations> InformationsList
        {
            get
            {
                return m_informationsList;
            }
            set
            {
                m_informationsList = value;
            }
        }
        
        public GameRolePlayShowMultipleActorsMessage(List<GameRolePlayActorInformations> informationsList)
        {
            m_informationsList = informationsList;
        }
        
        public GameRolePlayShowMultipleActorsMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort(((short)(m_informationsList.Count)));
            int informationsListIndex;
            for (informationsListIndex = 0; (informationsListIndex < m_informationsList.Count); informationsListIndex = (informationsListIndex + 1))
            {
                GameRolePlayActorInformations objectToSend = m_informationsList[informationsListIndex];
                writer.WriteUShort(((ushort)(objectToSend.TypeID)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            int informationsListCount = reader.ReadUShort();
            int informationsListIndex;
            m_informationsList = new System.Collections.Generic.List<GameRolePlayActorInformations>();
            for (informationsListIndex = 0; (informationsListIndex < informationsListCount); informationsListIndex = (informationsListIndex + 1))
            {
                GameRolePlayActorInformations objectToAdd = ProtocolTypeManager.GetInstance<GameRolePlayActorInformations>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_informationsList.Add(objectToAdd);
            }
        }
    }
}
