//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Character.Choice
{
    using BlueSheep.Common.Protocol.Types.Game.Character.Choice;


    public class CharacterSelectionWithRemodelMessage : CharacterSelectionMessage
    {
        
        public const int ProtocolId = 6549;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private RemodelingInformation m_remodel;
        
        public virtual RemodelingInformation Remodel
        {
            get
            {
                return m_remodel;
            }
            set
            {
                m_remodel = value;
            }
        }
        
        public CharacterSelectionWithRemodelMessage(RemodelingInformation remodel)
        {
            m_remodel = remodel;
        }
        
        public CharacterSelectionWithRemodelMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            m_remodel.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_remodel = new RemodelingInformation();
            m_remodel.Deserialize(reader);
        }
    }
}
