//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Character.Choice
{
    using BlueSheep.Common.Protocol.Types.Game.Character.Choice;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class CharacterSelectedSuccessMessage : Message 
    {
        
        public new const int ID = 153;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private CharacterBaseInformations m_infos;
        
        public virtual CharacterBaseInformations Infos
        {
            get
            {
                return m_infos;
            }
            set
            {
                m_infos = value;
            }
        }
        
        private bool m_isCollectingStats;
        
        public virtual bool IsCollectingStats
        {
            get
            {
                return m_isCollectingStats;
            }
            set
            {
                m_isCollectingStats = value;
            }
        }
        
        public CharacterSelectedSuccessMessage(CharacterBaseInformations infos, bool isCollectingStats)
        {
            m_infos = infos;
            m_isCollectingStats = isCollectingStats;
        }
        
        public CharacterSelectedSuccessMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_infos.Serialize(writer);
            writer.WriteBoolean(m_isCollectingStats);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_infos = new CharacterBaseInformations();
            m_infos.Deserialize(reader);
            m_isCollectingStats = reader.ReadBoolean();
        }
    }
}
