//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System;


    [Serializable()]
    public class Hint : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint Gfx
        {
            get
            {
                return mGfx;
            }
            set
            {
                mGfx = value;
            }
        }
        
        private uint mGfx;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual uint MapId
        {
            get
            {
                return mMapId;
            }
            set
            {
                mMapId = value;
            }
        }
        
        private uint mMapId;
        
        public virtual uint RealMapId
        {
            get
            {
                return mRealMapId;
            }
            set
            {
                mRealMapId = value;
            }
        }
        
        private uint mRealMapId;
        
        public virtual int X
        {
            get
            {
                return mX;
            }
            set
            {
                mX = value;
            }
        }
        
        private int mX;
        
        public virtual int Y
        {
            get
            {
                return mY;
            }
            set
            {
                mY = value;
            }
        }
        
        private int mY;
        
        public virtual bool Outdoor
        {
            get
            {
                return mOutdoor;
            }
            set
            {
                mOutdoor = value;
            }
        }
        
        private bool mOutdoor;
        
        public virtual int SubareaId
        {
            get
            {
                return mSubareaId;
            }
            set
            {
                mSubareaId = value;
            }
        }
        
        private int mSubareaId;
        
        public virtual int WorldMapId
        {
            get
            {
                return mWorldMapId;
            }
            set
            {
                mWorldMapId = value;
            }
        }
        
        private int mWorldMapId;
        
        public virtual uint Level
        {
            get
            {
                return mLevel;
            }
            set
            {
                mLevel = value;
            }
        }
        
        private uint mLevel;
        
        public Hint()
        {
        }
    }
}
