//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Context.Fight
{
    using BlueSheep.Common.Protocol.Types.Game.Look;
    using BlueSheep.Common.Protocol.Types.Game.Context;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class GameFightTaxCollectorInformations : GameFightAIInformations
    {
        
        public new const int ID = 48;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ushort m_firstNameId;
        
        public virtual ushort FirstNameId
        {
            get
            {
                return m_firstNameId;
            }
            set
            {
                m_firstNameId = value;
            }
        }
        
        private ushort m_lastNameId;
        
        public virtual ushort LastNameId
        {
            get
            {
                return m_lastNameId;
            }
            set
            {
                m_lastNameId = value;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        public GameFightTaxCollectorInformations(ushort firstNameId, ushort lastNameId, sbyte level)
        {
            m_firstNameId = firstNameId;
            m_lastNameId = lastNameId;
            m_level = level;
        }
        
        public GameFightTaxCollectorInformations()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarShort(m_firstNameId);
            writer.WriteVarShort(m_lastNameId);
            writer.WriteSByte(m_level);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_firstNameId = reader.ReadVarUhShort();
            m_lastNameId = reader.ReadVarUhShort();
            m_level = reader.ReadSByte();
        }
    }
}
