//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay.Stats
{
    using BlueSheep.Common;
	using BlueSheep.Common.Protocol.Types;


    public class StatsUpgradeResultMessage : Message
    {
        
        public const int ProtocolId = 5609;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_result;
        
        public virtual byte Result
        {
            get
            {
                return m_result;
            }
            set
            {
                m_result = value;
            }
        }
        
        private ushort m_nbCharacBoost;
        
        public virtual ushort NbCharacBoost
        {
            get
            {
                return m_nbCharacBoost;
            }
            set
            {
                m_nbCharacBoost = value;
            }
        }
        
        public StatsUpgradeResultMessage(byte result, ushort nbCharacBoost)
        {
            m_result = result;
            m_nbCharacBoost = nbCharacBoost;
        }
        
        public StatsUpgradeResultMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_result);
            writer.WriteVarShort(m_nbCharacBoost);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_result = reader.ReadByte();
            m_nbCharacBoost = reader.ReadVarUhShort();
        }
    }
}
