//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.Inventory
{
    public class KamasUpdateMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 5537;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_kamasTotal;
        
        public virtual ulong KamasTotal
        {
            get
            {
                return m_kamasTotal;
            }
            set
            {
                m_kamasTotal = value;
            }
        }
        
        public KamasUpdateMessage(ulong kamasTotal)
        {
            m_kamasTotal = kamasTotal;
        }
        
        public KamasUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarLong(m_kamasTotal);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_kamasTotal = reader.ReadVarUhLong();
        }
    }
}
