//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.Context.Fight.Character
{
    using BlueSheep.Protocol.Types.Game.Context;
    using BlueSheep.Protocol;
	using BlueSheep.Protocol.Types;


    public class GameFightRefreshFighterMessage : Message
    {
        
        public const int ProtocolId = 6309;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private GameContextActorInformations m_informations;
        
        public virtual GameContextActorInformations Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public GameFightRefreshFighterMessage(GameContextActorInformations informations)
        {
            m_informations = informations;
        }
        
        public GameFightRefreshFighterMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_informations.TypeID)));
            m_informations.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_informations = ProtocolTypeManager.GetInstance<GameContextActorInformations>(reader.ReadUShort());
            m_informations.Deserialize(reader);
        }
    }
}
