//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay.Houses.Guild
{
    using BlueSheep.Common;


    public class HouseGuildNoneMessage : Message
    {
        
        public const int ProtocolId = 5701;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_houseId;
        
        public virtual uint HouseId
        {
            get
            {
                return m_houseId;
            }
            set
            {
                m_houseId = value;
            }
        }
        
        private int m_instanceId;
        
        public virtual int InstanceId
        {
            get
            {
                return m_instanceId;
            }
            set
            {
                m_instanceId = value;
            }
        }
        
        private bool m_secondHand;
        
        public virtual bool SecondHand
        {
            get
            {
                return m_secondHand;
            }
            set
            {
                m_secondHand = value;
            }
        }
        
        public HouseGuildNoneMessage(uint houseId, int instanceId, bool secondHand)
        {
            m_houseId = houseId;
            m_instanceId = instanceId;
            m_secondHand = secondHand;
        }
        
        public HouseGuildNoneMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarInt(m_houseId);
            writer.WriteInt(m_instanceId);
            writer.WriteBoolean(m_secondHand);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_houseId = reader.ReadVarUhInt();
            m_instanceId = reader.ReadInt();
            m_secondHand = reader.ReadBoolean();
        }
    }
}
