//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context.Roleplay.Spell
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class SpellForgetUIMessage : Message 
    {
        
        public new const int ID = 5565;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private bool m_open;
        
        public virtual bool Open
        {
            get
            {
                return m_open;
            }
            set
            {
                m_open = value;
            }
        }
        
        public SpellForgetUIMessage(bool open)
        {
            m_open = open;
        }
        
        public SpellForgetUIMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_open);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_open = reader.ReadBoolean();
        }
    }
}
