//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Context
{
    using BlueSheep.Common.Protocol.Types.Game.Context;
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class GameContextMoveElementMessage : Message 
    {
        
        public new const int ID = 253;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private EntityMovementInformations m_movement;
        
        public virtual EntityMovementInformations Movement
        {
            get
            {
                return m_movement;
            }
            set
            {
                m_movement = value;
            }
        }
        
        public GameContextMoveElementMessage(EntityMovementInformations movement)
        {
            m_movement = movement;
        }
        
        public GameContextMoveElementMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_movement.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_movement = new EntityMovementInformations();
            m_movement.Deserialize(reader);
        }
    }
}
