//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System.Collections.Generic;
    using System;


    [Serializable()]
    public class MapPosition : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual int PosX
        {
            get
            {
                return mPosX;
            }
            set
            {
                mPosX = value;
            }
        }
        
        private int mPosX;
        
        public virtual int PosY
        {
            get
            {
                return mPosY;
            }
            set
            {
                mPosY = value;
            }
        }
        
        private int mPosY;
        
        public virtual bool Outdoor
        {
            get
            {
                return mOutdoor;
            }
            set
            {
                mOutdoor = value;
            }
        }
        
        private bool mOutdoor;
        
        public virtual int Capabilities
        {
            get
            {
                return mCapabilities;
            }
            set
            {
                mCapabilities = value;
            }
        }
        
        private int mCapabilities;
        
        public virtual int NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private int mNameId;
        
        public virtual bool ShowNameOnFingerpost
        {
            get
            {
                return mShowNameOnFingerpost;
            }
            set
            {
                mShowNameOnFingerpost = value;
            }
        }
        
        private bool mShowNameOnFingerpost;
        
        public virtual List<AmbientSound> Sounds
        {
            get
            {
                return mSounds;
            }
            set
            {
                mSounds = value;
            }
        }
        
        private List<AmbientSound> mSounds = new List<AmbientSound>();
        
        public virtual List<List<int>> Playlists
        {
            get
            {
                return mPlaylists;
            }
            set
            {
                mPlaylists = value;
            }
        }
        
        private List<List<int>> mPlaylists = new List<List<int>>();
        
        public virtual int SubAreaId
        {
            get
            {
                return mSubAreaId;
            }
            set
            {
                mSubAreaId = value;
            }
        }
        
        private int mSubAreaId;
        
        public virtual int WorldMap
        {
            get
            {
                return mWorldMap;
            }
            set
            {
                mWorldMap = value;
            }
        }
        
        private int mWorldMap;
        
        public virtual bool HasPriorityOnWorldmap
        {
            get
            {
                return mHasPriorityOnWorldmap;
            }
            set
            {
                mHasPriorityOnWorldmap = value;
            }
        }
        
        private bool mHasPriorityOnWorldmap;
        
        public virtual bool IsUnderWater
        {
            get
            {
                return mIsUnderWater;
            }
            set
            {
                mIsUnderWater = value;
            }
        }
        
        private bool mIsUnderWater;
        
        public MapPosition()
        {
        }
    }
}
