//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.DataCenter
{
    using System;


    [Serializable()]
    public class Waypoint : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual uint MapId
        {
            get
            {
                return mMapId;
            }
            set
            {
                mMapId = value;
            }
        }
        
        private uint mMapId;
        
        public virtual uint SubAreaId
        {
            get
            {
                return mSubAreaId;
            }
            set
            {
                mSubAreaId = value;
            }
        }
        
        private uint mSubAreaId;
        
        public Waypoint()
        {
        }
    }
}
