//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Context.Roleplay.Emote
{
    public class EmoteAddMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 5644;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private sbyte m_emoteId;
        
        public virtual sbyte EmoteId
        {
            get
            {
                return m_emoteId;
            }
            set
            {
                m_emoteId = value;
            }
        }
        
        public EmoteAddMessage(sbyte emoteId)
        {
            m_emoteId = emoteId;
        }
        
        public EmoteAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteSByte(m_emoteId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_emoteId = reader.ReadSByte();
        }
    }
}
