//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Interactive.Skill
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class SkillActionDescriptionTimed : SkillActionDescription
    {
        
        public new const int ID = 103;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private sbyte m_time;
        
        public virtual sbyte Time
        {
            get
            {
                return m_time;
            }
            set
            {
                m_time = value;
            }
        }
        
        public SkillActionDescriptionTimed(sbyte time)
        {
            m_time = time;
        }
        
        public SkillActionDescriptionTimed()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(m_time);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_time = reader.ReadSByte();
        }
    }
}
