//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Interactive.Skill
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    public class SkillActionDescription 
    {
        
        public new const int ID = 102;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ushort m_skillId;
        
        public virtual ushort SkillId
        {
            get
            {
                return m_skillId;
            }
            set
            {
                m_skillId = value;
            }
        }
        
        public SkillActionDescription(ushort skillId)
        {
            m_skillId = skillId;
        }
        
        public SkillActionDescription()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_skillId);
        }
        
        public void Deserialize(IDataReader reader)
        {
            m_skillId = reader.ReadVarUhShort();
        }
    }
}
