//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Actions.Fight
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class FightTemporarySpellBoostEffect : FightTemporaryBoostEffect
    {
        
        public new const int ID = 207;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ushort m_boostedSpellId;
        
        public virtual ushort BoostedSpellId
        {
            get
            {
                return m_boostedSpellId;
            }
            set
            {
                m_boostedSpellId = value;
            }
        }
        
        public FightTemporarySpellBoostEffect(ushort boostedSpellId)
        {
            m_boostedSpellId = boostedSpellId;
        }
        
        public FightTemporarySpellBoostEffect()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarShort(m_boostedSpellId);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_boostedSpellId = reader.ReadVarUhShort();
        }
    }
}
