//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System;


    [Serializable()]
    public class VeteranReward : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint RequiredSubDays
        {
            get
            {
                return mRequiredSubDays;
            }
            set
            {
                mRequiredSubDays = value;
            }
        }
        
        private uint mRequiredSubDays;
        
        public virtual uint ItemGID
        {
            get
            {
                return mItemGID;
            }
            set
            {
                mItemGID = value;
            }
        }
        
        private uint mItemGID;
        
        public virtual uint ItemQuantity
        {
            get
            {
                return mItemQuantity;
            }
            set
            {
                mItemQuantity = value;
            }
        }
        
        private uint mItemQuantity;
        
        public VeteranReward()
        {
        }
    }
}
