//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Character.Status
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class PlayerStatusExtended : PlayerStatus
    {
        
        public new const int ID = 414;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private string m_message;
        
        public virtual string Message
        {
            get
            {
                return m_message;
            }
            set
            {
                m_message = value;
            }
        }
        
        public PlayerStatusExtended(string message)
        {
            m_message = message;
        }
        
        public PlayerStatusExtended()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUTF(m_message);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_message = reader.ReadUTF();
        }
    }
}
