//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    using BlueSheep.Engine.Types;

 	 public class ExchangeErrorMessage : Message 
    {
        
        public new const int ID = 5513;
        
        public override int MessageID
        {
            get
            {
                return ID;
            }
        }
        
        private byte m_errorType;
        
        public virtual byte ErrorType
        {
            get
            {
                return m_errorType;
            }
            set
            {
                m_errorType = value;
            }
        }
        
        public ExchangeErrorMessage(byte errorType)
        {
            m_errorType = errorType;
        }
        
        public ExchangeErrorMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_errorType);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_errorType = reader.ReadByte();
        }
    }
}
