//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Interactive
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    public class MapObstacle 
    {
        
        public new const int ID = 200;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ushort m_obstacleCellId;
        
        public virtual ushort ObstacleCellId
        {
            get
            {
                return m_obstacleCellId;
            }
            set
            {
                m_obstacleCellId = value;
            }
        }
        
        private byte m_state;
        
        public virtual byte State
        {
            get
            {
                return m_state;
            }
            set
            {
                m_state = value;
            }
        }
        
        public MapObstacle(ushort obstacleCellId, byte state)
        {
            m_obstacleCellId = obstacleCellId;
            m_state = state;
        }
        
        public MapObstacle()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_obstacleCellId);
            writer.WriteByte(m_state);
        }
        
        public void Deserialize(IDataReader reader)
        {
            m_obstacleCellId = reader.ReadVarUhShort();
            m_state = reader.ReadByte();
        }
    }
}
