//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    using BlueSheep.Protocol;
    
    
    public class PortalInformation 
    {
        
        public new const int ID = 466;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private int m_portalId;
        
        public virtual int PortalId
        {
            get
            {
                return m_portalId;
            }
            set
            {
                m_portalId = value;
            }
        }
        
        private short m_areaId;
        
        public virtual short AreaId
        {
            get
            {
                return m_areaId;
            }
            set
            {
                m_areaId = value;
            }
        }
        
        public PortalInformation(int portalId, short areaId)
        {
            m_portalId = portalId;
            m_areaId = areaId;
        }
        
        public PortalInformation()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            writer.WriteInt(m_portalId);
            writer.WriteShort(m_areaId);
        }
        
        public void Deserialize(IDataReader reader)
        {
            m_portalId = reader.ReadInt();
            m_areaId = reader.ReadShort();
        }
    }
}
