//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class TreasureHuntStepFight : TreasureHuntStep
    {
        
        public new const int ID = 462;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        public TreasureHuntStepFight()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
        }
    }
}
