//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Context.Roleplay.TreasureHunt
{
    public class TreasureHuntStepFollowDirectionToPOI : TreasureHuntStep
    {
        
        public new const int ID = 461;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private byte m_direction;
        
        public virtual byte Direction
        {
            get
            {
                return m_direction;
            }
            set
            {
                m_direction = value;
            }
        }
        
        private ushort m_poiLabelId;
        
        public virtual ushort PoiLabelId
        {
            get
            {
                return m_poiLabelId;
            }
            set
            {
                m_poiLabelId = value;
            }
        }
        
        public TreasureHuntStepFollowDirectionToPOI(byte direction, ushort poiLabelId)
        {
            m_direction = direction;
            m_poiLabelId = poiLabelId;
        }
        
        public TreasureHuntStepFollowDirectionToPOI()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteByte(m_direction);
            writer.WriteVarShort(m_poiLabelId);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_direction = reader.ReadByte();
            m_poiLabelId = reader.ReadVarUhShort();
        }
    }
}
