//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.Protocol.Types.Game.Data.Items
{
    using System.Collections.Generic;
    using BlueSheep.Common.Protocol.Messages;
    using BlueSheep.Common.Protocol.Types;
    
    
    using BlueSheep.Protocol;
    
    
    public class GoldItem : Item
    {
        
        public new const int ID = 123;
        
        public virtual int TypeID
        {
            get
            {
                return ID;
            }
        }
        
        private ulong m_sum;
        
        public virtual ulong Sum
        {
            get
            {
                return m_sum;
            }
            set
            {
                m_sum = value;
            }
        }
        
        public GoldItem(ulong sum)
        {
            m_sum = sum;
        }
        
        public GoldItem()
        {
        }
        
        public void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarLong(m_sum);
        }
        
        public void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_sum = reader.ReadVarUhLong();
        }
    }
}
