//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Basic
{
    public class BasicWhoIsRequestMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 181;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_verbose;
        
        public virtual bool Verbose
        {
            get
            {
                return m_verbose;
            }
            set
            {
                m_verbose = value;
            }
        }
        
        private string m_search;
        
        public virtual string Search
        {
            get
            {
                return m_search;
            }
            set
            {
                m_search = value;
            }
        }
        
        public BasicWhoIsRequestMessage(bool verbose, string search)
        {
            m_verbose = verbose;
            m_search = search;
        }
        
        public BasicWhoIsRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_verbose);
            writer.WriteUTF(m_search);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_verbose = reader.ReadBoolean();
            m_search = reader.ReadUTF();
        }
    }
}
