//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Common.DataCenter
{
    using System;


    [Serializable()]
    public class AmbientSound : PlaylistSound, IData
    {
        
        public virtual int CriterionId
        {
            get
            {
                return mCriterionId;
            }
            set
            {
                mCriterionId = value;
            }
        }
        
        private int mCriterionId;
        
        public virtual uint SilenceMin
        {
            get
            {
                return mSilenceMin;
            }
            set
            {
                mSilenceMin = value;
            }
        }
        
        private uint mSilenceMin;
        
        public virtual uint SilenceMax
        {
            get
            {
                return mSilenceMax;
            }
            set
            {
                mSilenceMax = value;
            }
        }
        
        private uint mSilenceMax;
        
        public virtual int Typeid
        {
            get
            {
                return mTypeid;
            }
            set
            {
                mTypeid = value;
            }
        }
        
        private int mTypeid;
        
        public AmbientSound()
        {
        }
    }
}
