//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSheep.Protocol.Messages.Game.House
{
    using BlueSheep.Protocol;


    public class HouseTeleportRequestMessage : Message
    {
        
        public const int ProtocolId = 6726;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_houseId;
        
        public virtual uint HouseId
        {
            get
            {
                return m_houseId;
            }
            set
            {
                m_houseId = value;
            }
        }
        
        private int m_houseInstanceId;
        
        public virtual int HouseInstanceId
        {
            get
            {
                return m_houseInstanceId;
            }
            set
            {
                m_houseInstanceId = value;
            }
        }
        
        public HouseTeleportRequestMessage(uint houseId, int houseInstanceId)
        {
            m_houseId = houseId;
            m_houseInstanceId = houseInstanceId;
        }
        
        public HouseTeleportRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarInt(m_houseId);
            writer.WriteInt(m_houseInstanceId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_houseId = reader.ReadVarUhInt();
            m_houseInstanceId = reader.ReadInt();
        }
    }
}
