//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageBot.Protocol.Messages.Game.Inventory.Items
{
    public class ObtainedItemMessage : Message
    {
        
        protected override int ProtocolId { get; set; } = 6519;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_genericId;
        
        public virtual ushort GenericId
        {
            get
            {
                return m_genericId;
            }
            set
            {
                m_genericId = value;
            }
        }
        
        private uint m_baseQuantity;
        
        public virtual uint BaseQuantity
        {
            get
            {
                return m_baseQuantity;
            }
            set
            {
                m_baseQuantity = value;
            }
        }
        
        public ObtainedItemMessage(ushort genericId, uint baseQuantity)
        {
            m_genericId = genericId;
            m_baseQuantity = baseQuantity;
        }
        
        public ObtainedItemMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarShort(m_genericId);
            writer.WriteVarInt(m_baseQuantity);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_genericId = reader.ReadVarUhShort();
            m_baseQuantity = reader.ReadVarUhInt();
        }
    }
}
